"""delete uniqueness constraint

Revision ID: 82ad3f05e53a
Revises: 5e5288f72f77
Create Date: 2026-02-26 16:46:16.272688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ad3f05e53a'
down_revision: Union[str, Sequence[str], None] = '5e5288f72f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('requests_rep_document_number_key'), 'requests', type_='unique')
    op.drop_constraint(op.f('requests_rep_phone_key'), 'requests', type_='unique')
    op.drop_index(op.f('ix_requests_nit_company'), table_name='requests')
    op.create_index(op.f('ix_requests_nit_company'), 'requests', ['nit_company'], unique=False)
    op.drop_index(op.f('ix_requests_rep_email'), table_name='requests')
    op.create_index(op.f('ix_requests_rep_email'), 'requests', ['rep_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_rep_email'), table_name='requests')
    op.create_index(op.f('ix_requests_rep_email'), 'requests', ['rep_email'], unique=True)
    op.drop_index(op.f('ix_requests_nit_company'), table_name='requests')
    op.create_index(op.f('ix_requests_nit_company'), 'requests', ['nit_company'], unique=True)
    op.create_unique_constraint(op.f('requests_rep_phone_key'), 'requests', ['rep_phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('requests_rep_document_number_key'), 'requests', ['rep_document_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
