"""creación de entidad Company y UserCompany

Revision ID: 8d4e42aef6fa
Revises: 975e5f583043
Create Date: 2026-02-20 22:36:08.528460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4e42aef6fa'
down_revision: Union[str, Sequence[str], None] = '975e5f583043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=False),
    sa.Column('nit', sa.String(), nullable=False),
    sa.Column('economic_sector', sa.Enum('PRIMARY', 'INDUSTRIAL', 'SERVICES', name='economic_sector'), nullable=False),
    sa.Column('economic_activity', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('NATURAL', 'LEGAL', name='entity_type'), nullable=False),
    sa.Column('is_legally_constituted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_nit'), 'company', ['nit'], unique=True)
    op.create_table('user_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_empresa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company')
    op.drop_index(op.f('ix_company_nit'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
