"""add fields to users

Revision ID: 975e5f583043
Revises: 9270056e2782
Create Date: 2026-02-12 20:29:00.639549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975e5f583043'
down_revision: Union[str, Sequence[str], None] = '9270056e2782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('users', sa.Column('document_type', sa.String(), nullable=False))
    op.add_column('users', sa.Column('document_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_users_document_number'), 'users', ['document_number'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_document_number'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'document_number')
    op.drop_column('users', 'document_type')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
