"""users's phone can be null, and delete cascade users company

Revision ID: aa718ed0beec
Revises: 093b2eed3338
Create Date: 2026-02-28 19:29:37.445197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa718ed0beec'
down_revision: Union[str, Sequence[str], None] = '093b2eed3338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_company_company_id_fkey'), 'user_company', type_='foreignkey')
    op.drop_constraint(op.f('user_company_user_id_fkey'), 'user_company', type_='foreignkey')
    op.create_foreign_key(None, 'user_company', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_company', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'user_company', type_='foreignkey')
    op.drop_constraint(None, 'user_company', type_='foreignkey')
    op.create_foreign_key(op.f('user_company_user_id_fkey'), 'user_company', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_company_company_id_fkey'), 'user_company', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
