"""initial

Revision ID: c1eca7ca22aa
Revises: 
Create Date: 2026-02-25 23:17:46.896938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1eca7ca22aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=False),
    sa.Column('nit', sa.String(), nullable=False),
    sa.Column('economic_sector', sa.String(), nullable=True),
    sa.Column('economic_activity', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('NATURAL', 'LEGAL', name='entity_type'), nullable=False),
    sa.Column('is_legally_constituted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_nit'), 'company', ['nit'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rep_name', sa.String(), nullable=False),
    sa.Column('rep_email', sa.String(), nullable=False),
    sa.Column('rep_phone', sa.String(), nullable=False),
    sa.Column('rep_document_type', sa.Enum('CC', 'CE', name='document_type'), nullable=False),
    sa.Column('rep_document_number', sa.String(), nullable=False),
    sa.Column('legal_name_company', sa.String(), nullable=False),
    sa.Column('trade_name_company', sa.String(), nullable=False),
    sa.Column('nit_company', sa.String(), nullable=False),
    sa.Column('economic_activity', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('NATURAL', 'LEGAL', name='entity_type'), nullable=False),
    sa.Column('is_legally_constituted', sa.Boolean(), nullable=False),
    sa.Column('usuarios_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='status'), nullable=False),
    sa.Column('reason_for_rejection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rep_document_number'),
    sa.UniqueConstraint('rep_phone')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_nit_company'), 'requests', ['nit_company'], unique=True)
    op.create_index(op.f('ix_requests_rep_email'), 'requests', ['rep_email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'LEGAL_REPRESENTATIVE', 'USER', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('CC', 'CE', name='document_type'), nullable=False),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_document_number'), 'users', ['document_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('user_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_empresa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_document_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_requests_rep_email'), table_name='requests')
    op.drop_index(op.f('ix_requests_nit_company'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_company_nit'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
