"""add_tax_fileds_to_company

Revision ID: e1e7f691c143
Revises: aa718ed0beec
Create Date: 2026-03-20 17:02:43.061018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e7f691c143'
down_revision: Union[str, Sequence[str], None] = 'aa718ed0beec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    regime_type_enum = sa.Enum('SIMPLE', 'ORDINARY', name='regime_type')
    regime_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('regime_type', regime_type_enum, nullable=True))
    op.add_column('company', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('is_vat_responsible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'is_vat_responsible')
    op.drop_column('company', 'tax_rate')
    op.drop_column('company', 'regime_type')
    sa.Enum(name='regime_type').drop(op.get_bind())
    # ### end Alembic commands ###
