"""fix json fields

Revision ID: ef9dab731d82
Revises: d2124c683980
Create Date: 2026-03-23 21:32:48.446971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9dab731d82'
down_revision: Union[str, Sequence[str], None] = 'd2124c683980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_datasets', sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('raw_datasets', sa.Column('etl_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_datasets', 'etl_summary')
    op.drop_column('raw_datasets', 'column_mapping')
    # ### end Alembic commands ###
